sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t aleksandrasmoter/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aleksandrasmoter/docker-react npm run test
